### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by gpgreenleaf** [rgreen1207/FishOps#8]
> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                           Process: us.fishops.android.fishops, PID: 5247
>                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{us.fishops.android.fishops/us.fishops.android.fishops.WeatherActivity}: java.lang.IllegalArgumentException: invalid provider: null
>                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
>                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
>                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
>                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
>                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                               at android.os.Looper.loop(Looper.java:148)
>                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                               at java.lang.reflect.Method.invoke(Native Method)
>                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                                            Caused by: java.lang.IllegalArgumentException: invalid provider: null
>                                                                               at android.location.LocationManager.checkProvider(LocationManager.java:1704)
>                                                                               at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1194)
>                                                                               at us.fishops.android.fishops.WeatherActivity.getPosition(WeatherActivity.java:63)
>                                                                               at us.fishops.android.fishops.WeatherActivity.onCreate(WeatherActivity.java:42)
>                                                                               at android.app.Activity.performCreate(Activity.java:6237)
>                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
>                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
>                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
>                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
>                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
>                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                               at android.os.Looper.loop(Looper.java:148) 
>                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
>                                                                               at java.lang.reflect.Method.invoke(Native Method) 
>                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by gpgreenleaf** [comment]
With the solving of issue #3 the weather API is able to use the Google Maps API to gather weather data, so this problem is now fixed as well.
